// <auto-generated />
using System;
using ClassLibrary1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassLibrary1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240420171426_AddTabelaAppTechnicalVisits")]
    partial class AddTabelaAppTechnicalVisits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary2.Entidades.TechnicalVisits", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataDeAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDoServico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataReprogramacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilialDoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraTermino")
                        .HasColumnType("interval");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TempoAtendimento")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("AppTechnicalVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
